# docker-compose.yml

version: '3.3'

services:
  tq-redis:
    container_name: tq-redis
    image: redis:5.0.6-alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  tq-server:
    build:
      context: ./app
    # entrypoint: ./docker-entrypoint.sh
    command: python app.py
    container_name: tq-server
    depends_on:
      - tq-redis
    environment:
      - REDIS_URL=redis://tq-redis:6379/0
    ports:
      - 5000:5000

  pat-server:
    build:
      context: ./app
    # entrypoint: ./docker-entrypoint.sh
    command: python truckq.py
    container_name: pat-server
    

volumes:  
  redis_data: